# Generated by Django 4.2.1 on 2025-06-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_teams_created_by'),
        ('contacts', '0005_alter_contact_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='contact_teams', to='teams.teams'),
        ),
    ]
