# Generated by Django 4.2.1 on 2025-05-15 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='attachments',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachment_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
