# Generated by Django 4.2.1 on 2025-05-15 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_authconfig_alter_attachments_created_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthConfig',
            new_name='GoogleAuthConfig',
        ),
    ]
