# Generated by Django 4.2.1 on 2025-05-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_user_username_alter_attachments_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
