# Generated by Django 4.2.1 on 2025-05-16 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_user_email_alter_user_username'),
        ('common', '0011_rename_authconfig_googleauthconfig'),
    ]

    operations = [
    ]
