# Generated by Django 4.2.1 on 2025-05-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_merge_20250516_1219'),
        ('common', '0012_merge_20250516_1235'),
    ]

    operations = [
    ]
