# Generated by Django 4.2.1 on 2025-06-10 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role_permission_control', '0001_initial'),
        ('common', '0013_merge_20250519_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to='role_permission_control.role'),
        ),
    ]
